---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobless

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobless
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobless
subjects:
 - kind: ServiceAccount
   name: jobless
roleRef:
  kind: Role
  name: jobless
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobless
  template:
    metadata:
      labels:
        app: jobless
    spec:
      containers:
      - name: jobless
        image: public.ecr.aws/l7t2e6a6/jobless:0.0.4
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
      serviceAccountName: jobless
